apiVersion: apps/v1
kind: Deployment
metadata:
 name: conversao-temp
spec:
  selector:
    matchLabels:
      app: conversao-temp
  template:
    metadata:
      labels:
        app: conversao-temp
    spec:
      containers:
        - name: conversao-temp
          image: marlonmelgarejo/conversao-temperatura:v1
          ports:
          - containerPort: 8080